name = "colo-do"
main = "core/src/worker.ts"
compatibility_date = "2024-12-01"

# Routes
routes = [
  { pattern = "colo.do", custom_domain = true }
]

# Durable Objects for testing colo placement
[durable_objects]
bindings = [
  { name = "COLO_DO", class_name = "ColoDO" }
]

[[migrations]]
tag = "v1"
new_classes = ["ColoDO"]
